export const FETCH_SEARCH_RESULTS='FETCH_SEARCH_RESULTS';


export const AUTH_USER='AUTH_USER';
export const UNAUTH_USER='UNAUTH_USER';
export const AUTH_ERROR='AUTH_ERROR';
export const FETCH_MESSAGE='FETCH_MESSAGE';
export const FETCH_USER_BOOKS='FETCH_USER_BOOKS';
export const FETCH_ALL_BOOKS='FETCH_ALL_BOOKS';
export const FETCH_USER='FETCH_USER';
export const CLEAR_MESSAGE='CLEAR_MESSAGE';
